package com.nudge.core.model

import kotlinx.serialization.Serializable

// ─────────────────────────────────────────────────────────────────────────────
// Nudge — a proactive surface of a forgotten or time-sensitive intent.
// ─────────────────────────────────────────────────────────────────────────────

enum class NudgeStatus {
    /** Nudge is scheduled and waiting to be surfaced. */
    SCHEDULED,

    /** Nudge has been shown to the user. */
    SHOWN,

    /** User acknowledged the nudge. */
    ACKNOWLEDGED,

    /** User dismissed the nudge. */
    DISMISSED,

    /** The nudge expired without user interaction. */
    EXPIRED,
}

/**
 * A proactive reminder surfaced by NUDGE when it detects a forgotten
 * or time-sensitive intent.
 *
 * Nudges are generated by the [NudgeEngine] and scheduled via WorkManager.
 */
@Serializable
data class Nudge(
    val id: String,
    val intentId: String,
    val message: String,
    val scheduledAt: Long,                      // epoch millis
    val shownAt: Long? = null,
    val status: NudgeStatus = NudgeStatus.SCHEDULED,
)
